In [15]:
# import cv2

# # LOAD IMAGE AND TAG DICTIONARY
# tags = cv2.imread('data/two_tags_ARUCO_ORIGINAL.png')
# arucoDict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_ARUCO_ORIGINAL)

# # DETECT TAGS IN IMAGE
# corners, ids, rejects = cv2.aruco.detectMarkers(cv2.cvtColor(tags, cv2.COLOR_BGR2GRAY), arucoDict)

# # DRAW DETECTION AND SAVE FILE
# detection = cv2.aruco.drawDetectedMarkers(tags, corners, borderColor=(255, 0, 0))
# cv2.imwrite('detection_two_tags_ARUCO_ORIGINAL.png', detection)
## DETECT TAGS IN IMAGE
# corners, ids, rejects = cv2.aruco.detectMarkers(cv2.cvtColor(tags, cv2.COLOR_BGR2GRAY), arucoDict)

import cv2 as cv

dictionary = cv.aruco.getPredefinedDictionary(cv.aruco.DICT_ARUCO_ORIGINAL)
parameters =  cv.aruco.DetectorParameters()
detector = cv.aruco.ArucoDetector(dictionary, parameters)

frame = cv.imread('data/two_tags_ARUCO_ORIGINAL.png')

markerCorners, markerIds, rejectedCandidates = detector.detectMarkers(frame)

detection = cv2.aruco.drawDetectedMarkers(frame, markerCorners, markerIds, borderColor=(255, 0, 0))
print(markerCorners)
print(markerIds)
print(rejectedCandidates)

cv2.imwrite('detection_two_tags_ARUCO_ORIGINAL.png', detection)


(array([[[113., 113.],
        [412., 113.],
        [412., 412.],
        [113., 412.]]], dtype=float32), array([[[563., 563.],
        [862., 563.],
        [861., 862.],
        [563., 862.]]], dtype=float32))
[[192]
 [ 17]]
(array([[[605., 595.],
        [658., 604.],
        [648., 830.],
        [595., 821.]]], dtype=float32), array([[[682., 771.],
        [825., 768.],
        [829., 824.],
        [686., 829.]]], dtype=float32), array([[[682., 685.],
        [825., 682.],
        [829., 738.],
        [686., 743.]]], dtype=float32), array([[[155., 156.],
        [198., 155.],
        [199., 198.],
        [156., 199.]]], dtype=float32))


True

In [20]:
import numpy as np
import cv2
# # LOAD CORRECT TAG DICTIONARY
arucoDict = cv.aruco.getPredefinedDictionary(cv.aruco.DICT_ARUCO_ORIGINAL)

SIZE = 500 # pixels

# CREATE ARRAY FOR MARKER
marker = np.zeros((SIZE, SIZE, 1), dtype=np.uint8)

# DRAW AND SAVE MARKER
ID = 0
cv2.aruco.generateImageMarker(arucoDict, ID, SIZE, marker, 1)
cv2.imwrite('DICT_ARUCO_ORIGINAL_id_{}_{}.png'.format(ID, SIZE), marker)


True